### ISSUE TITLE
change default import folder

### ISSUE THREAD

**Issue by adbenitez** [webxdc/store#120]
by default the import command tries to import from ./import folder, that has no practical use, more since currently the cwd is the folder where the assets are (usually the extracted folder with the binary and assets) 

it is better to not have any default and request to pass a folder explicitly, or use `.` current working directory, which is not good right now for the previously mentioned issue of cwd needing to be the folder where the assets folder is

**Comment by Septias** [comment]
I believe the whole cwd discussion is kind of useless as we have #119 ?

**Comment by Septias** [comment]
I find it way more intuitive to have import xdcs nicely separated from the bot binary and assets-folder. If you want to have the cwd, you can still give that as an explicit path. For me the `import/` default is better than defaulting to '.'

**Comment by adbenitez** [comment]
I would recommend not having any default then, it is not a big deal to provide ./import as argument and it is more work to have to create an import folder just so you can use the import command without passing the folder,

but I am also fine with keeping the default, just think it is unnecessary, not that useful

**Comment by adbenitez** [comment]
> yes, no default is fine. Just require a path to a file or a dir.

that would be actually a real improvement, currently it is only supported to import a folder which is inconvenient
