### ISSUE TITLE
feat: Make it possible to remove apps from the store

### ISSUE THREAD

**Issue by link2xt** [webxdc/store#133]
Command `xdcstore list` or `xdcstore ls` should list existing applications on the command line for admin to inspect.
It should output applications with unique IDs that can be used in other commands.

`xdcstore remove <app-id>` or `xdcstore rm <app-id>` should remove the application from the database.

Ideally both commands should work regardless of whether the bot is running or not.

**Comment by hpk42** [comment]
i wonder  what it takes to make a removal of app/version also work in the frontend?  cc @septias

**Comment by Septias** [comment]
Reintroducing the 'removed' array in tho update response.

**Comment by hpk42** [comment]
Suppose i import a new version of an app, and then find out it's broken 
and then want to remove the version of the app from the store. 
How to do that? 

"Remove whole app, re-add the last working version of the app" 
would work but a more direct way to invalidate a version 
is worth a thought i think.

**Comment by Septias** [comment]
Atm .xdcs with the same same are simply overwritten, so rolling back a version without rewriting that is impossible

**Comment by adbenitez** [comment]
> Atm .xdcs with the same same are simply overwritten, so rolling back a version without rewriting that is impossible

to keep it simple, I think that behavior is fine for now, and you likely used the old version already in some chat (that is why you downloaded it) so user can reuse that already sent instances, we can think about fancy stuff like rolling back to previous downloaded version in the future but I think it is fine to keep it simple for now :pray:

**Comment by hpk42** [comment]
k, so @adbenitez and @septias : you are in favor of just removing a whole app-id then, as @link2xt suggested, right? 
fine for me for now -- so just to be sure everything is simple and easy:
 
What would be the effect on the frontend, 
- the frontend has downloaded myapp/v2 
- stop the bot, remove the "myapp" app_id
- import myapp/v1 into the bot 
- trigger app-index refresh on the frontend

Would myapp/v1 now be the thing i share/forward, or still myapp/v2?

**Comment by adbenitez** [comment]
> Would myapp/v1 now be the thing i share/forward, or still myapp/v2?

local cache should always be in sync with remote cache from bot, if bot says now that the latest release is v1 then discard v2 and download v1, if bot is downgrading is probably because v2 had a bug, so better not to try to be too smart and keeping local cache because it is bigger version etc

btw, (context: the CLI) then when importing there could be an option to force the overriding of a newer version, oth removing and then adding the old version will work as well
