### ISSUE TITLE
fix: Use version/app_id for frontend caching

### ISSUE THREAD

**Issue by Septias** [webxdc/store#136]
Using an app_id/version is maybe not needed at the moment but might lead to better reliability in the future. 
How exactly an implementation could look like is still part of discussion, for further information see this comment thread:
https://github.com/webxdc/store/pull/132#discussion_r1249843186

**Comment by Septias** [comment]
I would like to close this because atm it doesn't seem like a version/app_id cache is needed - it even came in handy in the past that the code is simpler (only app_id caching). If we need it for real, we can still add it later imo.

**Comment by hpk42** [comment]
k, let's put it to rest for now.
