### ISSUE TITLE
Frontend tests fail with Node.js 20

### ISSUE THREAD

**Issue by link2xt** [webxdc/store#152]
https://github.com/webxdc/store/pull/142#issuecomment-1620216852

**Comment by Septias** [comment]
Would like to close this as there is nothing we can do against it in this repo and it's also not a real problem as nothing breaks atm. As soon as something breaks we will notice I believe

**Comment by Septias** [comment]
Nice, thank you :)

**Comment by Septias** [comment]
closing this as it is not a real problem for the bot atm
