### ISSUE TITLE
prevent double-starting of bot

### ISSUE THREAD

**Issue by hpk42** [webxdc/store#156]
happened multiple times to me now that i start a bot using the same data (".config/xdcstore") twice. 
Could xdcstore refuse to run if there already is an instance running?

**Comment by Septias** [comment]
Don't have a good solution on that from the top of my head. Maybe a file that can be locked by one instance could work but there are maybe cleaner solutions. I guess @link2xt could maybe have a good idea?

**Comment by hpk42** [comment]
ok, it's not a big issue for now.  Maybe we can rather make sure that our upcoming recommended way of deploying (systemd) tries to prevent double-start. closing for now.
