### ISSUE TITLE
Do not send updated XDCs without user request

### ISSUE THREAD

**Issue by link2xt** [webxdc/store#166]
Currently when user requests a new app index, bot also sends download responses for each updated app, even though user did not request these .xdc updates:
https://github.com/webxdc/store/blob/50931d8e94c835062476d917c2906381b9663af8/src/request_handlers/store.rs#L116-L123

I likely missed a discussion on this, but I do not like how this works for users with limied bandwidth. If some app makes minor releases every day, I do not want to update it, or only want to update it when I am on free Wi-Fi.

**Comment by Septias** [comment]
Had a discussion about this, I guess @hpk42 can tell you a bit more about it

**Comment by r10s** [comment]
unless things have changed again, imu, the "download" function does _not_ "download an app in some version" but "marks apps that the user wants to keep for sharing, in the most recent version". this includes initial download as well as subsequent downloads.

this way, always the most recent version is shared.

the advantage of this is less UI, eg. no need to offer two buttons (share and update) - and also, this seems to be more the gist of what the user usually wants. less things, the user has to take care of.

at "Details", there is an option to remove an app from caching.

for users with limited bandwidth - that is a valid consideration, however, decided to being ignored for now. in practise, we'll see if that really becomes and issue, eg. lots of larger apps  being updated every day, and how that relates to overall bandwidth consumption.

**Comment by Septias** [comment]
Nice summary @r10s

**Comment by Septias** [comment]
Are you okay with closing this @link2xt?
