### ISSUE TITLE
missing hint if there are no search results

### ISSUE THREAD

**Issue by r10s** [webxdc/store#168]
if nothing is found, a hint should be printed, maybe repeating the search term.

> No results for \"abcdef\" - Show all

"Show all" could be a link that ends the search.

maybe also hide the footer in case there are no results (or move it down so that it is clear it  does not belong to the search). otherwise, ppl will probably always hit "Update now" as this is the only remaining button

**Comment by Septias** [comment]
Saw and fixed that a few minutes ago in #167 lol
