### ISSUE TITLE
show number of apps in search bar

### ISSUE THREAD

**Issue by hpk42** [webxdc/store#178]
Would be nice to show the number of apps in the search bar. 
![Screenshot from 2023-07-17 18-20-31](https://github.com/webxdc/store/assets/73579/d401a339-b186-42e6-a298-4f095b31ecaf)

**Comment by Septias** [comment]
The absolute number of apps or the apps filtered?

**Comment by r10s** [comment]
i think holger means to change the placeholder to sth as "Search 23 webxdc apps".



as this placeholder is not shown when there is a "filter" (a search string set) it
