### ISSUE TITLE
use a code formatter

### ISSUE THREAD

**Issue by Simon-Laux** [webxdc/store#195]
I recommend/like prettier. But anything predictable will do.

**Comment by Septias** [comment]
We use eslint already.

**Comment by Simon-Laux** [comment]
linting !== formatting

For me there is too much openness in the eslint fixing, like it allows more variants of code formatting, where prettier is a lot stricter. for example prettier enforces a max line length where this is not the case with eslint fix.

**Comment by Simon-Laux** [comment]
try this out: format a document with prettier, then run `eslint fix`, Observe that it does not return to the previous state of the code.

**Comment by Septias** [comment]
https://antfu.me/posts/why-not-prettier
