### ISSUE TITLE
feat: set avatar and display name

### ISSUE THREAD

**Issue by missytake** [webxdc/store#207]
Right now, the store bot does not have a display name and an avatar at all. There should be at least a default display name and avatar.

Ideally there would be a CLI command to set the display name and avatar. Something like `xdcstore set-profile 'webxdc store' --avatar ~/avatar.png`.

There should also be a default avatar and display name, set if it is empty currently.

**Comment by hpk42** [comment]
IMO it's good that the displayname is/contains the e-mail address in case one is using different instances.  So i think it should be fine for now to just set the avatar to the store-xdc icon.
