### ISSUE TITLE
Disable Eruda debugger on the main branch

### ISSUE THREAD

**Issue by link2xt** [webxdc/store#220]
It is currently always enabled here, but should be enabled only for PRs:
https://github.com/webxdc/store/blob/85059a178c3629312510a1610947ec9773e74c7d/.github/workflows/ci.yaml#L83-L84

**Comment by adbenitez** [comment]
I am not sure about only for PRs, ex. the testing bot also needs to test current master branch, wouldn't be better to have an "stable" branch or release tags and then build for deployment in those?

**Comment by adbenitez** [comment]
ex. we already have `release.yml` that will release for production on version tags, the `ci.yml` only builds testing stuff
