### ISSUE TITLE
Setup frontend testing CI

### ISSUE THREAD

**Issue by link2xt** [webxdc/store#36]
It would be nice to setup some CI for the frontend.

Nothing fancy, no end-to-end testing against the bot, just mock the basic webxdc APIs and e.g. have a test that when the .xdc is opened, the app list is displayed, then when update is clicked an update request is sent, then when an update arrives the app list refreshes and has an new/updated app in it.

Even one such test would help catching regressions that happen due to dependency updates or a syntax/method name error in JS that throws an error in the browser engine.

We are using testcafe in desktop: https://github.com/deltachat/deltachat-desktop/pull/3251
[cypress](https://www.cypress.io/) is also good

**Comment by adbenitez** [comment]
once this issue is solved then https://github.com/webxdc/appstore-bot/issues/78 can be worked on
