### ISSUE TITLE
Build release tarballs for deployment

### ISSUE THREAD

**Issue by link2xt** [webxdc/store#38]
Deploying the bot from the source code requires Node.js, Rust, `pnpm` and `cargo`. To make deployment on the server easy, we need release tarballs.

The bot is not in the releasable state yet, but as a first step we can make a `scripts/dist.sh` script which will build the frontend and the bot binary, put the binary together with the `bot-data/` directory containing the frontend into a tarball and put a resulting `.tar.gz` into `dist/` directory.

The resulting tarball can already be used to deploy the bot on machines without `npm` and Rust installed, and the script can be reused later to build release tarballs in CI.

**Comment by Septias** [comment]
I have no Idea how to do that, so would greatly appreciate help!
