### ISSUE TITLE
Add GitHub Actions workflow to generate preview tarballs for PRs

### ISSUE THREAD

**Issue by link2xt** [webxdc/store#40]
Now that a `scripts/dist.sh` script to generate release tarballs is added in #38, we can add a GHA workflow to generate release tarballs for each PR.

Workflow should be triggered on pull request, [upload the artifact](https://github.com/actions/upload-artifact) and post a link to the artifact as a status or the comment. To post statuses or comments [actions/github-script](https://github.com/actions/github-script) can be used.

**Comment by Septias** [comment]
Can you care about this @link2xt?

**Comment by Septias** [comment]
Nice :)
