### ISSUE TITLE
Add a way to get the bot version via Delta Chat for bug reporting

### ISSUE THREAD

**Issue by link2xt** [webxdc/store#41]
When the bot is deployed, it would be nice to have a way to get the bot version for bugreports.

E.g. when building the bot with the `scripts/dist.sh` script, put the git tag/commit into a file in the bot assets (`bot-data`) that the bot can read and reply with when user sends a `/version` command, or include the version in webxdc updates for the frontend to display in the footer.

**Comment by Septias** [comment]
Using the tarball should not be the only option to run the bot imo

**Comment by adbenitez** [comment]
ideally the CLI should have a --version option to check version, and the webxdc store should also have some version tag somewhere, maybe in an "About" section where then we can also explain to devs how to submit their apps
