### ISSUE TITLE
CI: check that autogenerated ts-rs files are always updated

### ISSUE THREAD

**Issue by link2xt** [webxdc/store#65]
These files have to be updated and add noise to the review tab, e.g. in https://github.com/webxdc/appstore-bot/pull/62/files

Documentation and CI should be checked to run `cargo` first and generate frontend afterwards if this is a dependency for the frontend.

**Comment by Septias** [comment]
What do you think @link2xt ?

**Comment by Septias** [comment]
Not needed imo. Build is fine even if those are not up to date. Those are only for developers and if it matters they will update them.
