### ISSUE TITLE
implement app updates for the app index

### ISSUE THREAD

**Issue by Septias** [webxdc/store#73]
* submitted apps should have an `app_id` and `version` fields in the manifest.toml file
* the bot will detect if the imported app is an upgrade of an already existing app on the index
* when the xdcstore frontend request the bot to send the updated index metadata, it also sends the app_id and version of downloaded apps
* when the bot receives an update request from the xdcstore frontend, besides the app index metadata it also checks the `app_id`s and `version`s of downladed apps and if there is a newer version, sends them one by one in new status-updates to the xdcstore frontend.
* use integer for `app_id`

hence update of downloaded apps happen automatically when the user use the app and a "update index" request is sent, because of this, a way to remove downloaded apps from cache/local-storage is needed, so user have a way to stop the updates of an app downloaded once to try but never wanted/used anymore, for that aspect see issue https://github.com/webxdc/store/issues/123

**Comment by adbenitez** [comment]
UPDATE: for **a)**, https://github.com/webxdc/appstore-bot/issues/66 already exists

**Comment by Septias** [comment]
Your Idea was to remove it in some pr. If we have proper versioning we can get rid of all this moving to different folder etc, just have on folder with all the webxdcs in it and when run, the bot will just compare all versions and update if needed.

**Comment by adbenitez** [comment]
> What is the "`keep files` importing problem"?

currently if you run the cli to import the same folder with apps, they will be imported as duplicates, also if you try to import an updated version of an already existing app
