### ISSUE TITLE
Turn XDC responses for each .xdc into variants of a single type

### ISSUE THREAD

**Issue by link2xt** [webxdc/store#85]
Currently `UpdateResponse`, `DownloadResponse` etc. are all different types. When they are serialized, the only way to distinguish one from another is to look at the fields they have.

This leads to code like this:
https://github.com/webxdc/store/blob/c1496279ca5dd6ff776c9ee1a39abacc9ec94879/frontend/src/utils.ts#L3-L5

Or this:
https://github.com/webxdc/store/blob/c1496279ca5dd6ff776c9ee1a39abacc9ec94879/frontend/src/entry-points/review.tsx#L26-L28

This does not scale, as soon as some other response gets an `okay` field, you need to use another field to look at.

If responses were variants of a single type, it would be possible to look at its name, e.g. `DownloadResponse` would serialize into
```
{"DownloadResponse": ...}
``` 
and to check if it is a download response you only need to check `Object.prototype.hasOwnProperty.call(p, 'DownloadResponse')`.

This is a follow-up to #21 which was about requests.

**Comment by Septias** [comment]
In general, I would not like to group _all_ message types into like two enums (One for requests and one for responses) as they currently belong to their respective modules (`request_handlers/shop.rs`, `request_handlers/submit.rs`) where duplication is allowed and maybe even wanted to have simpler reasoning module wise. 
For the request/response types that will be reused for all Webxdcs I understand the  reasoning and will make a commit in `sk/store_versioning` with a close refernce for this. Is that fine?

**Comment by Septias** [comment]
I don't really understand why you want to make change it event though it's not yet an issue, but okay, I'll create a short pr.

**Comment by Septias** [comment]
The core problem has been solved by me already, but I think it would be nice to have a way to destinguish the webxdc updates send by you from all the other ones you just receive
