### ISSUE TITLE
Separate assets from data

### ISSUE THREAD

**Issue by link2xt** [webxdc/store#93]
We need to distinguishing between the assets, which are read-only (could be owned by root and only readable by the bot), and the data.

Currently they are mixed. Assets are
- bot-data/store.xdc
- bot-data/review-helper.xdc
- bot-data/submit-helper.xdc

Data is:
- bot-data/xdcs/ (installed .xdcs)
- bot-db/bot.db (bot database accessed via sqlx)
- deltachat.db (delta chat core database)
- bot-data/1o1_invite_qr.png
- bot-data/genesis_invite_qr.png

The binary can go anywhere, you just need to point to it from the systemd unit. Could be dropped into /usr/local/bin/xdcstore or something like this, or into $HOME/.local/bin if you don't have the permissions to install software system-wide. $HOME/.local/bin is actually a part of the XDG specification as well: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Bot assets should go into XDG_DATA_DIRS, which usually means /usr/local/share/xdcstore or /usr/share/xdcstore or $HOME/.local/share/xdcstore
These are read-only, bot should not write here. Only the installation script or package manager should write the assets during the installation process.

Core database, blobdir, bot database and installed XDCs should all be contained in some folder, probably the working directory or $HOME/.config/xdcstore, with a command-line option that can be changed with a --config option.

**Comment by Septias** [comment]
You want to care about this? @link2xt
